import * as THREE from '../shared/vendor/three.module.js';
import {PointerLockControls} from '../shared/vendor/addons/controls/PointerLockControls.js';
import {GLTFLoader} from '../shared/vendor/addons/loaders/GLTFLoader.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0xc4cec1);scene.fog=new THREE.Fog(0xc4cec1,50,115);const camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.018,230);const mobile=matchMedia('(pointer:coarse)').matches;const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.1:1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.24;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);const controls=new PointerLockControls(camera,document.body);
scene.add(new THREE.HemisphereLight(0xf4f7ff,0x665a49,2.9));scene.add(new THREE.AmbientLight(0xfff1dc,1.45));const sun=new THREE.DirectionalLight(0xffe3b9,2.8);sun.position.set(-15,26,-9);sun.castShadow=!mobile;sun.shadow.mapSize.set(mobile?512:1024,mobile?512:1024);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;scene.add(sun);
const presets={
 outside:{p:[-5.359,1.65,-.537],t:[-4.684,1.40,1.378],label:'Départ extérieur · avancez vers la porte pour entrer'},garden:{p:[-12.5,1.65,-17.2],t:[-4.2,1.45,-11.86],label:'Jardin V18 · arbres, haies et sols PBR'},kitchen:{p:[-5.829,1.65,3.525],t:[-3.487,1.20,2.836],label:'Cuisine au sud du séjour'},living:{p:[-7.037,1.65,5.862],t:[-5.749,1.20,8.616],label:'Séjour du RDC'},stairs:{p:[-5.321,1.65,2.957],t:[-7.161,1.30,4.976],label:'Escalier 16 marches'},upper:{p:[-7.321,4.30,5.450],t:[-5.832,3.80,4.790],label:'Palier de l’étage'},bed1:{p:[-7.834,4.30,7.915],t:[-7.724,3.60,9.534],label:'Chambre 1'},bed2:{p:[-5.390,4.30,5.044],t:[-4.099,3.60,6.850],label:'Chambre 2'},bed3:{p:[-4.689,4.30,2.959],t:[-3.142,3.60,4.007],label:'Chambre 3'},bathN:{p:[-6.420,4.30,11.239],t:[-4.997,3.60,11.085],label:'Salle de bains nord'},bathS:{p:[-6.264,4.30,1.057],t:[-5.349,3.60,1.787],label:'Salle de bains sud'}
};
let house,furnitureVisible=true;const status=document.querySelector('#status'),loading=document.querySelector('#loading');
function isFurniture(name){const n=name.toUpperCase();return ['V12_KITCHEN','V12_DINING','V12_LIVING','V12_BEDROOM','V12_DRESSING','V12_SDB','V12_GF_WC','V12_UF_WC_TOILET','V12_LAUNDRY','V12_ENTRY_CLOSET','V12_BARSTOOL','V12_DINING_TABLE','V12_LIVING','V12_HEDGE','V12_TREE','V12_OUTDOOR'].some(p=>n.startsWith(p))}
function preset(key){const v=presets[key];camera.position.fromArray(v.p);camera.lookAt(new THREE.Vector3().fromArray(v.t));status.textContent=v.label;window.__lastPreset=key}preset('outside');
const loader=new GLTFLoader();loader.load('../shared/Chamagnieu_V18_ROOF_GROUND_REALISM.glb?v=18a',g=>{house=g.scene;house.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=!mobile;o.userData.isFurniture=isFurniture(o.name)}});scene.add(house);loading.classList.add('hide');status.textContent='Maison V18 chargée · toiture complète, sols et végétation visibles';window.__viewerReady=true;window.__viewerVersion='V18'},p=>{if(p.total){const pc=Math.round(100*p.loaded/p.total);status.textContent=`Téléchargement ${pc} %`;loading.textContent=`Ouverture rapide ${pc} %`}},e=>{window.__viewerFailed=true;window.__viewerError=e?.message||String(e);loading.innerHTML='<div><strong>Erreur V18</strong><small id="errdetail"></small><button id="retry3d">Réessayer</button> <a href="../rapide/">Galerie</a></div>';document.querySelector('#errdetail').textContent=window.__viewerError;document.querySelector('#retry3d').onclick=()=>location.reload();status.textContent='Erreur : '+window.__viewerError;console.error(e)});setTimeout(()=>{if(!window.__viewerReady&&!window.__viewerFailed)loading.innerHTML='Toujours en cours… <a href="../rapide/">Voir la galerie instantanée</a>'},12000);
document.querySelector('#start').onclick=()=>{preset('outside');if(!mobile)controls.lock();else status.textContent='Départ extérieur · utilisez ▲ pour entrer'};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset));document.querySelector('#furniture').onclick=e=>{furnitureVisible=!furnitureVisible;house?.traverse(o=>{if(o.userData.isFurniture)o.visible=furnitureVisible});e.currentTarget.textContent=furnitureVisible?'Masquer les meubles':'Afficher les meubles'};
const keys={};addEventListener('keydown',e=>keys[e.code]=true);addEventListener('keyup',e=>keys[e.code]=false);const clock=new THREE.Clock();function move(){const dt=Math.min(clock.getDelta(),.05),speed=(keys.ShiftLeft||keys.ShiftRight?6.0:2.6)*dt;if(keys.KeyW||keys.KeyZ||keys.ArrowUp||keys.TouchForward)controls.moveForward(speed);if(keys.KeyS||keys.ArrowDown||keys.TouchBack)controls.moveForward(-speed);if(keys.KeyA||keys.KeyQ||keys.ArrowLeft||keys.TouchLeft)controls.moveRight(-speed);if(keys.KeyD||keys.ArrowRight||keys.TouchRight)controls.moveRight(speed);if(keys.KeyE)camera.position.y+=speed;if(keys.KeyC)camera.position.y-=speed}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.setAnimationLoop(()=>{if(controls.isLocked)move();else clock.getDelta();renderer.render(scene,camera)});




// Commandes tactiles pour téléphone/tablette.
if(matchMedia('(pointer:coarse)').matches){
  document.querySelector('#start').textContent='Commencer dehors';
  const pad=document.createElement('div');pad.className='mobile-pad';pad.innerHTML='<button data-m="f">▲</button><button data-m="l">◀</button><button data-m="r">▶</button><button data-m="b">▼</button><span>Glissez sur l’image pour regarder</span>';document.body.append(pad);
  const map={f:'TouchForward',b:'TouchBack',l:'TouchLeft',r:'TouchRight'};
  pad.querySelectorAll('button').forEach(b=>{const k=map[b.dataset.m];b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys[k]=false))});
  let last=null;renderer.domElement.addEventListener('pointerdown',e=>{last=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId)});
  renderer.domElement.addEventListener('pointermove',e=>{if(!last)return;const dx=e.clientX-last[0],dy=e.clientY-last[1];last=[e.clientX,e.clientY];const eu=new THREE.Euler().setFromQuaternion(camera.quaternion,'YXZ');eu.y-=dx*.004;eu.x=Math.max(-1.45,Math.min(1.45,eu.x-dy*.004));camera.quaternion.setFromEuler(eu)});
  renderer.domElement.addEventListener('pointerup',()=>last=null);
}
